### ISSUE TITLE
Docker - Establish communication with module schema

### ISSUE THREAD

**Issue by ismisepaul** [OWASP/SecurityShepherd#367]
When MySQL server is run on a separate instance database levels no longer work as the users created for each of the schema is granted access to the schema from localhost;

```sql
GRANT USAGE ON *.* TO 'firstBloodyMessL'@'localhost' IDENTIFIED BY 'password';
DROP USER 'firstBloodyMessL'@'localhost';
CREATE USER 'firstBloodyMessL'@'localhost' IDENTIFIED BY 'firstBlooded';
GRANT SELECT ON `SqlInjLesson`.`tb_users` TO 'firstBloodyMessL'@'localhost';
```

The error seen when connecting from another host;
```bash
secshep_tomcat | FATAL admin at 172.30.0.1 from ?.?.?.? @ 27 Aug 12:10:36,809 [http-nio-8080-exec-3] (Database.java:193) - Unable to create database connection: java.sql.SQLException: Access denied for user 'firstBloodyMessL'@'172.30.0.4' (using password: YES)
secshep_tomcat | java.sql.SQLException: Access denied for user 'firstBloodyMessL'@'172.30.0.4' (using password: YES)
secshep_tomcat | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1078)
secshep_tomcat | 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4120)
secshep_tomcat | 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4052)
secshep_tomcat | 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:925)
secshep_tomcat | 	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1704)
secshep_tomcat | 	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1250)
secshep_tomcat | 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2483)
secshep_tomcat | 	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2516)
secshep_tomcat | 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2301)
secshep_tomcat | 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:834)
secshep_tomcat | 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
secshep_tomcat | 	at sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
secshep_tomcat | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
secshep_tomcat | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
secshep_tomcat | 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
secshep_tomcat | 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:416)
secshep_tomcat | 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:317)
secshep_tomcat | 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
secshep_tomcat | 	at java.sql.DriverManager.getConnection(DriverManager.java:247)
secshep_tomcat | 	at dbProcs.Database.getSqlInjLessonConnection(Database.java:189)
secshep_tomcat | 	at servlets.module.lesson.SqlInjectionLesson.getSqlInjectionResult(SqlInjectionLesson.java:133)
secshep_tomcat | 	at servlets.module.lesson.SqlInjectionLesson.doPost(SqlInjectionLesson.java:81)
secshep_tomcat | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
secshep_tomcat | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
secshep_tomcat | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
secshep_tomcat | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
secshep_tomcat | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
secshep_tomcat | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
secshep_tomcat | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
secshep_tomcat | 	at servlets.SetupFilter.doFilter(SetupFilter.java:39)
secshep_tomcat | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
secshep_tomcat | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
secshep_tomcat | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
secshep_tomcat | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
secshep_tomcat | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
secshep_tomcat | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
secshep_tomcat | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
secshep_tomcat | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
secshep_tomcat | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
secshep_tomcat | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
secshep_tomcat | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
secshep_tomcat | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
secshep_tomcat | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
secshep_tomcat | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
secshep_tomcat | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
secshep_tomcat | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
secshep_tomcat | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
secshep_tomcat | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
secshep_tomcat | 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ismisepaul** [comment]
Changes to how mysql docker is built

removing line
```bash
echo 'skip-name-resolve'; \
```
from

```bash
RUN mkdir -p /etc/mysql/conf.d \
	&& { \
		echo '[mysqld]'; \
		echo 'skip-host-cache'; \
		echo 'datadir = /var/lib/mysql'; \
		echo '!includedir /etc/mysql/conf.d/'; \
	} > /etc/mysql/my.cnf
```

Also adding hostname of tomcat server to grants. So both localhost and tomcat is included e.g.;
```sql
GRANT USAGE ON *.* TO 'firstBloodyMessL'@'localhost' IDENTIFIED BY 'password';
DROP USER 'firstBloodyMessL'@'localhost';
CREATE USER 'firstBloodyMessL'@'localhost' IDENTIFIED BY 'firstBlooded';
GRANT SELECT ON `SqlInjLesson`.`tb_users` TO 'firstBloodyMessL'@'localhost';

GRANT USAGE ON *.* TO 'firstBloodyMessL'@'secshep_tomcat.securityshepherd_default' IDENTIFIED BY 'password';
DROP USER 'firstBloodyMessL'@'secshep_tomcat.securityshepherd_default';
CREATE USER 'firstBloodyMessL'@'secshep_tomcat.securityshepherd_default' IDENTIFIED BY 'firstBlooded';
GRANT SELECT ON `SqlInjLesson`.`tb_users` TO 'firstBloodyMessL'@'secshep_tomcat.securityshepherd_default';

```
