### ISSUE TITLE
Docker build passes, but exeption during Tomcat startup: Invalid keystore format

### ISSUE THREAD

**Issue by rudosch** [OWASP/SecurityShepherd#595]
Docker build passes, but there's an "**Invalid keystore format**" exception when starting Tomcat with `docker-compose up`

```
11-Mar-2022 14:43:57.540 SEVERE [main] org.apache.catalina.core.StandardService.initInternal Failed to initialize connector [Connector[HTTP/1.1-8443]]
	org.apache.catalina.LifecycleException: Protocol handler initialization failed
		at org.apache.catalina.connector.Connector.initInternal(Connector.java:1032)
		at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
		at org.apache.catalina.core.StandardService.initInternal(StandardService.java:552)
		at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
		at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:848)
		at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
		at org.apache.catalina.startup.Catalina.load(Catalina.java:639)
		at org.apache.catalina.startup.Catalina.load(Catalina.java:662)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:303)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
	Caused by: java.lang.IllegalArgumentException: Invalid keystore format
		at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:100)
		at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:72)
		at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:246)
		at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1118)
		at org.apache.tomcat.util.net.AbstractJsseEndpoint.init(AbstractJsseEndpoint.java:223)
		at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:587)
		at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:74)
		at org.apache.catalina.connector.Connector.initInternal(Connector.java:1030)
		... 13 more
	Caused by: java.io.IOException: Invalid keystore format
		at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:663)
		at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
		at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
		at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
		at java.security.KeyStore.load(KeyStore.java:1445)
		at org.apache.tomcat.util.security.KeyStoreUtil.load(KeyStoreUtil.java:69)
		at org.apache.tomcat.util.net.SSLUtilBase.getStore(SSLUtilBase.java:216)
		at org.apache.tomcat.util.net.SSLHostConfigCertificate.getCertificateKeystore(SSLHostConfigCertificate.java:206)
		at org.apache.tomcat.util.net.SSLUtilBase.getKeyManagers(SSLUtilBase.java:282)
		at org.apache.tomcat.util.net.openssl.OpenSSLUtil.getKeyManagers(OpenSSLUtil.java:98)
		at org.apache.tomcat.util.net.SSLUtilBase.createSSLContext(SSLUtilBase.java:246)
		at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:98)
		... 20 more
```

System info:
- Ubuntu 20.04
- OpenJDK 11.0.14
- Docker 20.10.7
- Docker-compose 1.25.0
- Maven 3.6.3

**Comment by rudosch** [comment]
It seems that Java 8 must be installed, otherwise the keytool will generate a keystore file that Tomcat v8.5 will not be able to read.

See [https://bugs.openjdk.java.net/browse/JDK-8228481](https://bugs.openjdk.java.net/browse/JDK-8228481) and
[https://stackoverflow.com/questions/67766268/ioexception-in-java-8-when-reading-pkcs12-keystore-created-with-keytool-from-ope](https://stackoverflow.com/questions/67766268/ioexception-in-java-8-when-reading-pkcs12-keystore-created-with-keytool-from-ope)

I suggest that a note be added to the web page that it is mandatory to have Java8 installed.

**Comment by ismisepaul** [comment]
Thanks @rudosch,

Could you take a look at the pull request #598 and let me know if this will suffice to address this?

**Comment by rudosch** [comment]
This is the most minimal solution, but at least it's clear now.
Of course, it would be better to upgrade to at least JDK11 and Tomcat 8.5.76, but this would need a closer look and more time, I know.

BTW: are there any plans at all to work on new versions?

**Comment by ismisepaul** [comment]
@rudosch there's no solid plans, also I'll add that the database needs to be upgraded but these are all big tasks.

I've done the last bit of work there to push a new release so at least there's no more coding left to achieve that.

Once issue #611 is addressed I don't see a reason why there can't be a release.

Thanks again for your contribution

**Comment by spmishra121** [comment]
I am getting same error...

**docker tomcat environment details...**
 
TERM=xterm
VERSION=3.1
TOMCAT_DOCKER_VERSION=8-jre8-openjdk
DB_VERSION=10.5.8
MONGODB_VERSION=4.1.13
IMAGE_TOMCAT=owasp/security-shepherd
IMAGE_MARIADB=owasp/security-shepherd_mariadb
IMAGE_MONGO=owasp/security-shepherd_mongo
CONTAINER_TOMCAT=secshep_tomcat
CONTAINER_MARIADB=secshep_mariadb
CONTAINER_MONGO=secshep_mongo
DB_USER=root
DB_PASS=CowSaysMoo
DB_SERVER_IP=127.0.0.1
DB_PORT=3312
DB_BIND_ADDRESS=*
TLS_KEYSTORE_PASS=CowSaysMoo
TLS_KEYSTORE_FILE=shepherdKeystore.p12
ALIAS=tomcat
KEY_ALG=RSA
DNAME=cn=OwaspShepherd,ou=SecurityShepherd,o=OWASP,L=BaileÁthaCliath,ST=Laighin,C=IE
STORE_TYPE=pkcs12
HTTP_PORT=9090
HTTPS_PORT=443
DOCKER_NETWORK_NAME=securityshepherd_default
TEST_MYSQL_HOST=127.0.0.1
TEST_MYSQL_PORT=3306
TEST_MYSQL_PASSWORD=password
JAVA_HOME=/usr/local/openjdk-8
LANG=C.UTF-8
JAVA_VERSION=8u322
CATALINA_HOME=/usr/local/tomcat
TOMCAT_NATIVE_LIBDIR=/usr/local/tomcat/native-jni-lib
LD_LIBRARY_PATH=/usr/local/tomcat/native-jni-lib
GPG_KEYS=05AB33110949707C93A279E3D3EFE6B686867BA6 07E48665A34DCAFAE522E5E6266191C37C037D42 47309207D818FFD8DCD3F83F1931D684307A10A5 541FBE7D8F78B25E055DDEE13C370389288584E7 5C3C5F3E314C866292F359A8F3AD5C94A67F707E 765908099ACF92702C7D949BFA0C35EA8AA299F1 79F7026C690BAA50B92CD8B66A3AD3F4F22C4FED 9BA44C2621385CB966EBA586F72C284D731FABEE A27677289986DB50844682F8ACB77FC2E86E29AC A9C5DF4D22E99998D9875A5110C01C5A2F6059E7 DCFD35E0BF8CA7344752DE8B6FB21E8933C60243 F3A04C595DB5B6A5F1ECA43E3B7BBB100D811BBE F7DA48BB64BCB84ECBA7EE6935CD23C10D498E23
TOMCAT_MAJOR=8
TOMCAT_VERSION=8.5.76
TOMCAT_SHA512=7b84a311b2ba3b6c92eea5739275b45686ed893bc000c16ead0a3cfe7c166b12d42485e9eb9c40fe279d207a293c4de65db3107602794f2b8e6071bc4d2b53ed
RUN_USER=tomcat
HOME=/usr/local/tomcat

**Comment by rudosch** [comment]
@spmishra121 Which JDK version are you using on docker host ? It's important to use JDKv8 to run the correct keytool version during maven build.
